name: Code Tests

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run unit tests
        run: yarn test
      - name: Run coverage
        run: yarn test:cov